docs/config.md, server/core/connector.go, server/core/kafka2nats.go, server/core/kafka2stan.go, server/core/nats2kafka.go, server/core/stan2kafka.go
Close #10 
Bring golang template and 2 template functions (replace, substring) to help with "destination" (topic, subject, channel) definition.
Some performances related insights:
3K messages on master branch
```
{
"name": "NATS:> to Kafka:events",
"id": "zJapCmG5BUw7lFQgLnKkzV",
"connected": true,
"connects": 1,
"disconnects": 0,
"bytes_in": 22885,
"bytes_out": 22885,
"msg_in": 2999,
"msg_out": 2999,
"count": 2999,
"rma": 4142986.176725575,
"q50": 3541906.348870057,
"q75": 3914790.1003134795,
"q90": 4556933.919117645,
"q95": 4940597.268041236
}
```
3K messages using template (but a single `.Subject` value, so a single topic)
```
{
"name": "NATS:> to Kafka:event.{{ .Subject }}",
"id": "VV6N9CynhG8vNtJ8i1Q2rR",
"connected": true,
"connects": 1,
"disconnects": 0,
"bytes_in": 22885, …
```
=> Implements templated 'destination' (topic, subject, channel)

docs/config.md, server/core/connector.go, server/core/kafka2nats_test.go, server/core/kafka2stan_test.go, server/core/nats.go, server/core/nats2kafka_test.go, server/core/server_config_test.go, server/core/server_test.go, server/core/stan2kafka_test.go
- If DiscoverPrefix in NATSStreamingConfig object is not set, use
default value instead of passing the empty value which causes
connections to fail.
- Log all publish errors as ERR not notices (INF).
- Absence of channel in a STAN config should cause the bridge
to fail to start. Without channel specified, publishes to STAN
produce an invalid publish request.
- Update doc to point to "include" details for configuration parsing
and add IMPORTANT note that the include is using relative path.
The IDE has fixed some of the imports and fmt with missing spaces,
etc..
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
=> [FIXED] Several issues

server/core/connector.go, server/core/kafka2nats_test.go, server/core/nats.go, server/core/server.go
- When NATS connection is terminally closed (due to MaxReconnects
not being infinite), the bridge is shutdown. The process will now
also exit with a os.Exit(2) to notify docker/system that the exit
was "abnormal".
- On clean shutdown (ctrl+c) the streaming connection should be
closed *before* the NATS connection since with streaming, protocols
are sent to the streaming server and needs the low level NATS
connection.
- The STAN to Kafka connector was not using Errorf() to trace publish
errors to Kafka
- ensureReconnectTimer() was improperly calling itself on error
but continued for NATS/STAN and connectors, which was leading to
the timer be invoked many, many times..
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
=> [FIXED] Reconnect logic

.github/workflows/testing.yaml, .gitignore, Makefile, docs/buildandrun.md, server/core/nats2kafka_test.go
Currently, the makefile ignores Go test errors because it wants to
always run clean up. This change refactors the makefile to allow Go test
errors to be noticed and ensure that clean up runs.
In addition, it enables GODEBUG=x509ignoreCN=0 during tests to give us
some time to figure out how to generate certs with SANs. This is
temporary and should be removed soon.
=> Fix false positive tests

docs/buildandrun.md, server/core/nats2kafka_test.go
Even though it sounds like the server might work without the config, that doesn't seem to be the case.
```
$ ./nats-kafka 
2021/01/14 18:46:02.427410 [INF] starting NATS-Kafka Bridge, version 0.0-dev
2021/01/14 18:46:02.427513 [INF] server time is Thu Jan 14 18:46:02 PST 2021
2021/01/14 18:46:02.427520 [INF] connecting to NATS core
2021/01/14 18:46:02.428127 [ERR] error starting bridge, nats: no servers available for connection
2021/01/14 18:46:02.428169 [INF] stopping bridge
2021/01/14 18:46:02.428178 [INF] http monitoring stopped
```
This updates the doc to say that a config file is required.
=> Reword paragraph about config file

server/kafka/consumer.go, server/kafka/manager.go, server/kafka/producer.go
Currently, we don't honor the InsecureSkipVerify parameter. This causes
connection problems when connecting to Azure.
This change adds TLS config for InsecureSkipVerify when using SASL.
Resolves #26
=> Fix TLS config for SASL

server/core/connector.go, server/core/kafka2nats.go, server/core/kafka2stan.go, server/kafka/consumer.go, server/kafka/manager.go, server/kafka/producer.go
Currently, users can only choose between SASL and TLS insecure skip verify and full TLS. This change allows users to use SASL with full TLS.
=> Support connections with SASL and TLS

Makefile
I noticed we tried to run this rule, but it didn't exist. So I added it.
=> Add 'make clean' rule

README.md
We don't use Travis CI anymore for this project. This updates the badge for GitHub Actions.
=> Replace Travis build status badge with GitHub Actions

main.go
Currently, it's possible to pass invalid flag configuration when starting nats-kafka. This change checks the error from initialization and reports it.
=> Check flag initialization error

server/conf/conf.go, server/core/connector.go, server/core/jetstream2kafka.go, server/core/jetstream2kafka_test.go, server/core/kafka2jetstream.go, server/core/kafka2jetstream_test.go, server/core/nats.go, server/core/server.go, server/core/server_test.go
This adds JetStream support to nats-kafka. It's based off the NATS and STAN implementations.
Closes #41
You can run the tests locally like this. (Automatically sets up and tears down Docker containers and runs Go tests.)
```
make test
```
In addition, this is how I tested manually.
```sh
make setup-docker-test
nats-server -DVV -js
nats stream create --subjects baz mystream1
nats stream create --subjects bang mystream2
nats consumer add --target mytarget mystream2 myconsumer2
nats-kafka -c nats-kafka.conf
nats pub baz "hi $(date)"
nats sub mytarget
make teardown-docker-test
```
Here's the config file.
```
nats: {
Servers: ["localhost:4222"],
}
jetstream: {
maxwait: 5000,
}
connect: [
{
type: "JetStreamToKafka",
brokers: ["localhost:9092"]
id: "foo",
topic: "bar",
subject: "baz",
},
{
type: …
```
=> Add JetStream support

server/core/nats.go, server/core/nats2kafka_test.go
This skips trying to connect to JetStream if it's missing from the nats-kafka configuration.
=> Skip JetStream if not configured

.gitignore, go.mod, go.sum, server/kafka/partitioner.go, server/kafka/partitioner_test.go, server/kafka/producer.go
This PR adds an implementation of LeastBytes balancer which is compatible with the Sarama `Partitioner` interface. It routes messages based on the amount of bytes delivered to partitions. It uses key and value size in deciding the next partition. This implementation uses https://github.com/orcaman/concurrent-map to avoid global locking caused by a single mutex.
=> LeastBytes partitioner implementation

server/kafka/packer_utils.go, server/kafka/packer_utils_test.go, server/kafka/partitioner.go, server/kafka/partitioner_test.go, server/kafka/pb_schema_manager.go, server/kafka/pb_serializer.go
This PR fixes the `buildMessageIndexes` function where the indexBuf would not get the result of the loop variable. This also improves the `packer_utils` to use big endian instead of small to provide consistency throughout the code.
=> Bug fix in pbSerializer and code clean up

server/kafka/pb_deserializer.go, server/kafka/pb_serializer.go, server/kafka/producer_test.go
An issue exists in the protobuf serializer where the message indexes array length and contents are not written correctly causing the deserialization to fail. This PR correctly sets the array length as well as the message indexes array contents using varints and also changes the serializer test to decode the message and check for validity.
=> Write message indexes correctly in protobuf

.github/workflows/testing.yaml
Also removed go-version-file in "lint" section.
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
=> Did not have `go-version` for the test section

server/kafka/consumer.go
**Background**
In https://github.com/Shopify/sarama/issues/1192, a user reported seeing `read tcp <ip>:63133-><ip>:9092: i/o timeout` errors when consuming Kafka messages with a consumer group during rebalancing. As a response, Sarama updated their documentation and examples to indicate that the `ConsumeClaim` function should explicitly check for a completed `Context` (see: https://github.com/Shopify/sarama/pull/2240). It's possible that we may have run into the same problem when using `nats-kafka`, as we recently saw very similar errors in a production installation. 
**Description**
With this PR, we're updating nats-kafka's Kafka Consumer to align with the updated usage advice from the Sarama developers (https://github.com/Shopify/sarama/blob/main/examples/consumergroup/main.go).
=> Fixed Kafka bug with consumer groups and timeouts during repartitioning

.github/workflows/release.yaml, .github/workflows/testing.yaml
Bump various GitHub Actions versions to move away from those using the deprecated node.js 12 runtime, and so remove the warnings.
Quote the Golang version string for defensiveness against version number parsing and YAML string vs version numbers.
=> Bump GH Actions versions (Go; node12 deprecation)

docker-bake.hcl, server/conf/conf.go, server/core/connector.go, server/core/jetstream2kafka.go, server/core/jetstream2kafka_test.go, server/core/kafka2jetstream.go, server/core/server_test.go
add support to consume from streams that use sources:
```hcl
connect: [
{
type: "JetStreamToKafka",
brokers: ["127.0.0.1:9092"]
id: "Telemetry",
topic: "nats.telemetry",
subject: "foo.*",
durablename: "KafkaBridgeConsumer",
stream: foo_global # Stream that is composed of many streams.
},
],
```
=> Support bind stream JS option

conf/jetstream-kafka.conf, docs/config.md, server/core/connector.go, server/core/jetstream2kafka.go
This PR adds a feature that provides connecting a jetstream with multiple push subscribers with a queue group in order to provide horizontal scalability and fault tolerance support.
This may be a solution to the issue #88
=> Add QueueSubscriber Option for JetstreamToKafka

server/conf/conf.go, server/kafka/producer.go
Adds a `tls` option to the SASL block to opt into using TLS always:
```hcl
connect: [
{
type: "JetStreamToKafka",
brokers: ["<my-brokers>:9096","<my-brokers>:9096"]
id: "Telemetry",
topic: "foo",
subject: "foo",
durablename: "KafkaBridgeConsumer2",
stream: foo
sasl: {
"user": "admin",
"password": "secret",
"mechanism": "scram-sha-512",
"tls": true
}
},
],
```
=> Add SASL TLS option to always use tls
